### ISSUE TITLE
Add 2 new fields in payment

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#136]
Ad a drop down of countries, and is possible mark the user country based on the time zone of the browser. And an input for the zip code. If possible with real validation based on the selected country, more about the formatting, and not if it is really valid. 

And for this, please don't use any Google stuff ;)

**Comment by acidbiscuit** [comment]
@davidgatti 

For dropdown of countries we will store a static JSON of countries list.  
For pre-select of user's country, we would have to use third party API. Luckily, there are free services available that provide user country and zip code.  
Validating zip code is not a common practice and there should be a good reason for it. We would have to use paid third party API for that. Since we use stripe widget, it should handle all the validation as it is relevant to actual card information and for optional security, as far as I understand.

**Comment by davidgatti** [comment]
- country as static JSON, is perfect.
- zip code, you are right the widget should have the option to ask for that, the only thing I don't know is if, I have to set in the account settings to force that or you have to enable a flag in the widget config. Let me know what do you find out.

**Comment by acidbiscuit** [comment]
@davidgatti 
Stripe collects zip code by default and provides an option to hide the field. Is it different for you?  
We can also get the value from the widget to store it elsewhere.

**Comment by davidgatti** [comment]
No, all good, then enable it.
