### ISSUE TITLE
Add new profile menu called UI

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#214]
- after the personal info add a UI tab
- Add on the page an option to switch the UI theme from dark to light, and save the setting in cognito which will overwrite the OS setting if present.
- After that add a slider to be able to change the font size on the site. From normal to bigger options. And save the setting to cognito, and load it when the user visits the page

**Comment by acidbiscuit** [comment]
@davidgatti Changing font size may sound better that it works in action. Since we (Vuetify) does not use a single font size, we will have to introduce a multiplier and build a system to dynamically apply it to core Vuetify settings. I think zoom-in and zoom-out feature by browser works better with font sizing, since it changes actual viewport to adjust whole page content.

If you still want to go with it, please, provide any examples of font sizes and multipliers from a standard font size.

**Comment by davidgatti** [comment]
OK, lets drop the font thing.
