### ISSUE TITLE
Cash non changing data

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#88]
I'd like to have constantly visible data, like the avatar to be cashed in the browser memory, and when changed the cash get updated, and then synchronized with the back-end. If possible.

**Comment by acidbiscuit** [comment]
@davidgatti Manual caching is relevant when developing mobile applications. For browsers there is no need to implement such functionality since browser and service workers handle static content caching efficiently if correct headers are set for files.

I've added cache control header to avatar upload request and the rest should be handled by browser and service worker. Note that HTTPS is required for service worker caching.
